dir: "mocks"
filename: "{{.InterfaceName}}.go"
outpkg: mocks

packages:
  github.com/julez-dev/chatuino/emote:
    interfaces:
      TwitchEmoteFetcher:
      SevenTVEmoteFetcher:
      BTTVEmoteFetcher:
      FFZEmoteFetcher:
      EmoteStore:
      DisplayManager:
  github.com/julez-dev/chatuino/save/messagelog:
    interfaces:
      DB:
        configs:
          - mockname: DBVariadic
            unroll-variadic: true
  github.com/julez-dev/chatuino/badge:
    interfaces:
      BadgeFetcher:
      BadgeCache:
